### PR TITLE
Cleanup access rule handling when object is being created, rm context type

### PR DESCRIPTION
**Pull request by pjanik**
[#172226773]

Two changes:

1. The context access rule type is removed. It was never used for any kind of authorization. And its fields were a bit confusing (I guess `role` field wasn't necessary). I think it's better to remove it now and add when we really need it, maybe in some refined form and with tests. I guess at this point we should be sure that no app is using it.

2. I limited access rules that can be created when we create a new resource. Now there are just two options:
 - user is anonymous and requests "readWriteToken".
 - user is authenticated and requests a "user" access rule. In this case, it's no longer necessary to provide role. The user will be automatically assigned the "owner" role (since he's just creating this resource and it doesn't make much sense to revoke access to your own resource immediately).

I noticed these things when I was trying to write some reasonable tests for this logic. 

Tests are failing, but I'll open subsequent PR that includes these changes and a bunch of new tests. I'll merge this one only when the other one is also approved. Just trying to make this small change separate from hundreds of lines of tests.

### CODE REVIEW

**Comment by dougmartin** [comment]
@pjanik I've replaced myself with @scytacki as the reviewer.  The context role, while currently unused, was designed in by Scott and meant for future use by IoT apps like Dataflow.  I think he should be the one to weigh-in on whether it should be removed.

**Comment by pjanik** [comment]
@scytacki, I accidentally merged PR with tests into it. But the only thing to review here is the very first commit.

**Comment by pjanik** [comment]
So, the thing is that the current context rule implementation is just dead. It's a few types and string constants in the code, but there's no single line of code that actually makes use of them. None of the authorization paths knows that context type exists. We just never test against it. Plus, I'm not so sure if the actual types have the right fields. So, instead of trying to clarify that, I thought we can just remove a few types, so devs in the future don't have some false impression that they can break something if context rule needs to be modified. There are no paths in the current code that we could even use for testing. 

The only thing that comes to my mind would be an option for the user to let all the context/class members get AWS credentials. So, teacher could make a file editable by students. I could implement it and test it if it makes sense, and then context rule will be justified.

Otherwise, I think it's just dead code lines that might add a bit of confusion when someone is looking at the code for the first time. And when we come back to it, e.g. while implementing S3PrivateFolder or Iot Organization thing that you described, we can just add them back. No matter if we leave the current types or not, we'll have to change the code and release it.

Re migrations, I don't think they'd be necessary. Acess rule is just a custom object in existing `accessRules` array. So, it's mostly about updating the code so it understands new structures there. And whether we remove these lines of code or not shouldn't affect it.

**Comment by scytacki** [comment]
Regarding the migrations, I was thinking that if we remove the context rule type. Then we might decide to remove the rule type all together since the only other rule type was user. But now I remember that readWriteToken is a ruleType as well.

We also don't really have a production example of a "member" role. Users are always owners. But at least that part of the code is testable.

Your suggestion of adding an example of an owner adding a context rule with a role of member which then grants the "members" the same aws credentials as the owner, seems like it should be easy to implement and would then keep the code from being dead. It close to the S3Private idea. However I reviewed the design doc again and I think we might just do some broader refactoring in the future, so I think it is fine to just remove the code.

For reference: 
I updated the section on the S3Private support: https://docs.google.com/document/d/1Ud3lXQc1r7Ljch0o4HGCqS8s788yUggCgh2ZxbvaCNU/edit#heading=h.e3cu3pmupvum

And I also added a new section on a simplification that I think would remove any S3 or IoT specific code from the server side: https://docs.google.com/document/d/1Ud3lXQc1r7Ljch0o4HGCqS8s788yUggCgh2ZxbvaCNU/edit#heading=h.8o0xiulk00zj
There'd still be S3 and IoT specific template policy documents, but no objects or logic.

**Comment by pjanik** [comment]
> We also don't really have a production example of a "member" role.

I think the idea was to add these rules manually in Firestore web UI. But I don't know if it ever happened. 

> And I also added a new section on a simplification that I think would remove any S3 or IoT specific code from the server-side:

This would be great.

**Pull request merged**
